services:
  - name: cardio-app
    type: web
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SUPABASE_URL
        value: postgresql://postgres.bpcrrwgpwloehbnmmehn:lntuandat123@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GMAIL_CLIENT_ID_SEND
        sync: false
      - key: GMAIL_CLIENT_SECRET_SEND
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: GMAIL_SENDER
        sync: false
      - key: DEFAULT_SOCIAL_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
